---
title: "9.4  Introducción a Factorización LU"
author: "Monserrath Antonio Cordero"
date: "2025-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Matriz original
A <- matrix(c(
  1, 3, -2, 1,
  1, 1,  4, -1,
  2, 0,  1, -1,
  4, 2,  6, 1
), nrow = 4, byrow = TRUE)
Aorig <- A
A

```

```{r}
# Paso 1: Matriz identidad
I <- diag(4)
I

# Paso 2: Ampliar matriz con identidad
A <- cbind(A, I)
A

# Paso 3: Cálculo de multiplicadores
l21 <- A[2,1] / A[1,1]
l31 <- A[3,1] / A[1,1]
l41 <- A[4,1] / A[1,1]
c(l21, l31, l41)

# Paso 4: Eliminación columna 1
A[2,] <- A[2,] - l21 * A[1,]
A[3,] <- A[3,] - l31 * A[1,]
A[4,] <- A[4,] - l41 * A[1,]
A

# Paso 5: Intercambio de filas 2 y 3
tmp <- A[2,]; A[2,] <- A[3,]; A[3,] <- tmp
A

# Paso 6: Nuevos multiplicadores
l32 <- A[3,2] / A[2,2]
l42 <- A[4,2] / A[2,2]
c(l32, l42)

# Paso 7: Eliminar bajo pivote 2
A[3,] <- A[3,] - l32 * A[2,]
A[4,] <- A[4,] - l42 * A[2,]
A

# Paso 8: Normalizar fila 3
A[3,] <- A[3,] / A[3,3]
A

# Paso 9: Eliminación fila 4, columna 3
l43 <- A[4,3] / A[3,3]
A[4,] <- A[4,] - l43 * A[3,]
A

# Paso 10: Normalizar fila 4
A[4,] <- A[4,] / A[4,4]
A

# Paso 11: Sustitución hacia atrás
l34 <- A[3,4]; A[3,] <- A[3,] - l34 * A[4,]
l24 <- A[2,4]; A[2,] <- A[2,] - l24 * A[4,]
l14 <- A[1,4]; A[1,] <- A[1,] - l14 * A[4,]
A

# Paso 12: Más sustituciones
l23 <- A[2,3]; A[2,] <- A[2,] - l23 * A[3,]
l13 <- A[1,3]; A[1,] <- A[1,] - l13 * A[3,]
A

# Paso 13: Última sustitución
l12 <- A[1,2]; A[1,] <- A[1,] - l12 * A[2,]
A

# Paso 14: Extraer inversa
AInv <- A[,5:8]
AInv

# Paso 15: Verificación A * A^-1 = I
IdCalc <- Aorig %*% AInv
round(IdCalc, 5)
```

## FACTORIZACIÓN LU

```{r}
A <- matrix(c(
  1, 1, 1, 1,
  2, 3, 1, 5,
 -1, 1, -5, 3,
  3, 1, 7, -2
), nrow = 4, byrow = TRUE)
b <- matrix(c(10, 31, -2, 18), nrow = 4)

Ab <- cbind(A, b)
A <- Ab
A

# Eliminación paso a paso
l21 <- A[2,1]/A[1,1]
l31 <- A[3,1]/A[1,1]
l41 <- A[4,1]/A[1,1]

A[2,] <- A[2,] - l21 * A[1,]
A[3,] <- A[3,] - l31 * A[1,]
A[4,] <- A[4,] - l41 * A[1,]
A

l32 <- A[3,2]/A[2,2]
l42 <- A[4,2]/A[2,2]

A[3,] <- A[3,] - l32 * A[2,]
A[4,] <- A[4,] - l42 * A[2,]
A

l43 <- A[4,3]/A[3,3]
A[4,] <- A[4,] - l43 * A[3,]
A

# Matriz L
L <- diag(4)
L[2,1] <- l21; L[3,1] <- l31; L[4,1] <- l41
L[3,2] <- l32; L[4,2] <- l42
L[4,3] <- l43
L

# Matriz U
U <- A[,1:4]
U

# Verificación: A = L %*% U
Acalculada <- L %*% U
round(Acalculada, 5)

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```