---
title: "TAREA 7.4: Eliminación Gaussiana con Pivoteo Parcial"
author: "Monserrath Antonio Cordero"
output: html_document
date: "2025-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gauss_pivoteo_pasos <- function(A) {
  A <- as.matrix(A)
  n <- nrow(A)
  cat("Matriz aumentada inicial:\n")
  print(round(A, 6)); cat("\n")

  
  for (i in 1:(n - 1)) {
    # Pivoteo parcial
    max_row <- which.max(abs(A[i:n, i])) + i - 1
    if (max_row != i) {
      cat(paste("Intercambio fila", i, "<->", max_row, "\n"))
      A[c(i, max_row), ] <- A[c(max_row, i), ]
      print(round(A, 6)); cat("\n")
    }

    for (j in (i + 1):n) {
      factor <- A[j, i] / A[i, i]
      cat(paste("Eliminando A[", j, ",", i, "] con factor =", round(factor, 6), "\n"))
      A[j, i:ncol(A)] <- A[j, i:ncol(A)] - factor * A[i, i:ncol(A)]
      print(round(A, 6)); cat("\n")
    }
  }

  # Sustitución regresiva
  x <- rep(0, n)
  for (i in n:1) {
    if (i < n) {
      suma <- sum(A[i, (i+1):n] * x[(i+1):n])
    } else {
      suma <- 0
    }
    x[i] <- (A[i, n+1] - suma) / A[i, i]
  }

  cat("Solución final:\n")
  print(round(x, 6))
  return(x)
}


```

# --- EJERCICIO 1 ---
```{r}
A1 <- matrix(c(
  0.4, -1.5,  0.75, -20,
 -0.5, -15,   10,   -10,
 -10,  -9,    2.5,   30
), nrow = 3, byrow = TRUE)

gauss_pivoteo_pasos(A1)

```

# --- EJERCICIO 3 ---

```{r}
A3 <- matrix(c(
  0.003, 59.14,   59.17,
  5.291, -6.13,   46.78
), nrow = 2, byrow = TRUE)

gauss_pivoteo_pasos(A3)
```

# --- Ejercicio 5 ---

```{r}
A5 <- matrix(c(
  0.00031, 1.000000, 3.000000,
  1.00045534, 1.00034333, 7.000
), nrow = 2, byrow = TRUE)

gauss_pivoteo_pasos(A5)

```

# --- Ejercicio 7 ---


```{r}

A7 <- matrix(c(
  1/4, 1/5, 1/6,
  1/3, 1/4, 1/5,
  1/2, 1,   2
), nrow = 3, byrow = TRUE)

b7 <- c(9, 8, 8)

# Matriz aumentada
Ab7 <- cbind(A7, b7)

gauss_pivoteo_pasos(Ab7)

```

# --- Ejercicio 8 ---


```{r}
A8 <- matrix(c(
  1,   1/2, 1/3, 1/4, 1/6,
  1/2, 1/3, 1/4, 1/5, 1/7,
  1/3, 1/4, 1/5, 1/6, 1/8,
  1/4, 1/5, 1/6, 1/7, 1/9
), nrow = 4, byrow = TRUE)

gauss_pivoteo_pasos(A8)


```

# --- Ejercicio 9 ---

```{r}
A9 <- matrix(c(
  2, 1, -1, 1, -3, 7,
  1, 0,  2, -1, 1, 2,
  0, -2, -1, 1, -1, -5,
  3, 1, -4, 0, 5, 6,
  1, -1, -1, -1, 1, 3
), nrow = 5, byrow = TRUE)

gauss_pivoteo_pasos(A9)


```

# --- Ejercicio 10 ---

```{r}
A10 <- matrix(c(
  3.333, 15920, -10.333, 15913,
  2.222, 16.71, 9.612,   28.544,
  1.5611, 5.1791, 1.6852, 8.4254
), nrow = 3, byrow = TRUE)

gauss_pivoteo_pasos(A10)

```
