---
title: "Curso de Métodos Númericos"
output: html_document
date: "2025-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#INVERSA DE UNA MATRIZ

{r}
A=matrix(c(1,3,-2,1,1,4,-1,2,0,1,-1,4,2,6,1,2),nrow = 4,byrow = TRUE)
(A)
Aorig <- A


{r}
I=diag(4);(I)


{r}
AInv <- cbind(A,I); (AInv)
A <- AInv


{r}
L21 <- A[2,1]/A[1,1];(L21)
L31 <- A[2,1]/A[1,1];(L31)
L41 <- A[2,1]/A[1,1];(L41)


{r}
A[2,] <- A[2,]-L21*A[1,];
A[3,] <- A[3,]-L31*A[1,];
A[4,] <- A[4,]-L41*A[1,];
(A)


{r}
Atmp <- A[2,]
A[2,]<- A[3,]
A[3,]<- Atmp
(A)


{r}
L32 <- A[3,2]/A[2,2];(L32)
L42 <- A[4,2]/A[2,2];(L42)
(A)


{r}
A[3,] <- A[3,]-L32*A[2,];
A[4,] <- A[4,]-L42*A[2,];
(A)


{r}
esc <- 1/A[3,3]
A[3,] <- esc*A[3,]
(A)


{r}
L43 <- A[4,3]/A[3,3];(L43)


{r}
A[4,] <- A[4,]-L43*A[3,];
(A)


{r}
esc <- 1/A[4,4]
A[4,] <- esc*A[4,]
(A)



{r}
L34 <- A[3,4]/A[4,4];(L34); A[3,] <- A[3,]-L34*A[4,]
L34 <- A[3,4]/A[4,4];(L34); A[3,] <- A[3,]-L34*A[4,]
L14 <- A[1,4]/A[4,4];(L14); A[1,] <- A[1,]-L14*A[4,]
(A)



{r}
L23 <- A[2,3]/A[3,3];(L23); A[2,] <- A[2,]-L23*A[3,]
L13 <- A[1,3]/A[3,3];(L13); A[1,] <- A[1,]-L13*A[3,]
(A)


{r}
L23 <- A[2,3]/A[3,3];(L23); A[2,] <- A[2,]-L23*A[3,]
L13 <- A[1,3]/A[3,3];(L13); A[1,] <- A[1,]-L13*A[3,]
(A)



```{r}
L12 <- A[1,2]/A[2,2];(L12); A[1,] <- A[1,]-L12*A[2,]
(A)
```

```{r}
AInv <- A[,5:8]; (AInv)
```

```{r}
IdCalc <- Aorig%*%AInv; (IdCalc)
```
#factirizacion lu

#Ejemplo 1

```{r}
A=matrix(c(1,1,1,1,2,3,1,5,-1,1,1,-5,3,3,1,7,-2), byrow = TRUE, nrow = 4); (A)

```

```{r}
b=matrix(c(10,31,-2,17), nrow = 4); (b)

```

```{r}
Ab <- cbind(A,b);(Ab)
```

```{r}
A <- Ab;
L21 <- A[2,1]/A[1,1];(L21)
L31 <- A[3,1]/A[1,1];(L31)
L41 <- A[4,1]/A[1,1];(L41)

```

```{r}

A[2,] <-A[2,]-L21*A[1,]; (A[2,])
A[3,] <-A[3,]-L31*A[1,]; (A[3,])
A[4,] <-A[4,]-L41*A[1,]; (A[4,])
```

```{r}
(A)
```

```{r}
L32 <- A[3,4]/A[2,2];(L32)
L42 <- A[4,2]/A[2,2];(L42)
```

```{r}
A[3,] <- A[3,]-L32*A[2,];(A[3,])
A[4,] <- A[4,]-L42*A[2,];(A[4,])
```

```{r}
(A)
```

```{r}
L43 <- A[4,3]/A[3,3];(A[4,])

```

```{r}
(A)
```

```{r}
L=diag(4);(L)
```

```{r}
L[2,1] <- L21
L[3,1] <- L31
L[4,1] <- L41
L[3,1] <- L32
L[4,1] <- L42
L[4,1] <- L43
(L)

```

```{r}
U <- A[,1:4];(U)
```

```{r}
Acalculada <- L%*%U;(Acalculada)
```

#EJEMPLO 2
```{r}
A=matrix
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```