---
title: "MÉTODO DE GAUSS"
output: html_document
date: "2025-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ELIMINACIÓN GAUSSIANA CON PIVOTEO PARCIAL
 El sistema a resolver es:

5x+2y-3z+4w=-2
-x+y+z-3w=2
6x+6y+4z+w=0
x-y-z+w=2

```{r}
valores <- c(5,2,-3,4,-1,1,1,-3,6,6,4,1,-1,-1,-1,1)
A <- matrix(valores,nrow=4)
A <- t(A)
(A)
B<-  c(-1,2,0,2)

```

```{r}
AB <- cbind(A,B);(AB)
```

```{r}
R1 <- A[3,]
R2 <- A[1,]
R3 <- A[2,]
R4 <- A[4,]
NuevaA <- rbind(R1,R2,R3,R4);(NuevaA)
```


```{r}
AB <- NuevaA;(AB)
m1 <- -AB[2,1]/AB[1,1];(m1)
m2 <- -AB[3,1]/AB[1,1];(m2)
m3 <- -AB[4,1]/AB[1,1];(m3)
```

```{r}
NuevaA <- rbind(R1,R2,R3,R4);(NuevaA)

```
```{r}
R1 <- NuevaA[1,]
R2 <- NuevaA[3,]
R3 <- NuevaA[2,]
R4 <- NuevaA[4,]
AB <- rbind(R1,R2,R3,R4);(AB)
```

```{r}
m4 <- -AB[3,2]/AB[2,2];
m5 <- -AB[4,2]/AB[2,2];
R3 <- m4*AB[2,]+AB[3,];(R3)
R4 <- m5*AB[2,]+AB[4,];(R4)

NuevaA <- rbind(R1,R2,R3,R4);(NuevaA)
```
