---
title: "Polinomica"
author: "Monserrath Antonio Cordero"
date: "2025-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```



```{r}

A <- matrix(c(1, 1, 1,
              1, 2, 4,
              1, 4, 16), nrow = 3, byrow = TRUE)

b <- matrix(c(2, 3, 7), nrow = 3)

Ab <- cbind(A, b)
cat("Matriz aumentada inicial:\n")
print(Ab)


# ETAPA 1: Eliminación (columna 1)

m21 <- -Ab[2,1] / Ab[1,1]
m31 <- -Ab[3,1] / Ab[1,1]

Ab[2,] <- Ab[2,] + m21 * Ab[1,]
Ab[3,] <- Ab[3,] + m31 * Ab[1,]

cat("\nDespués de eliminar columna 1:\n")
print(Ab)


#  Eliminación (columna 2)

m32 <- -Ab[3,2] / Ab[2,2]

Ab[3,] <- Ab[3,] + m32 * Ab[2,]

cat("\nDespués de eliminar columna 2:\n")
print(Ab)


#  Sustitución hacia atrás


z <- Ab[3,4] / Ab[3,3]
y <- (Ab[2,4] - Ab[2,3] * z) / Ab[2,2]
x <- (Ab[1,4] - Ab[1,2] * y - Ab[1,3] * z) / Ab[1,1]

# --- Resultado ---
cat("\n--- Solución del sistema ---\n")
cat("x =", x, "\n")
cat("y =", y, "\n")
cat("z =", z, "\n")
```


```{r}
paso<- 0.01
a<- -1
b<- 6
x<- seq(a,b,paso)
head(x,10)
a0 <- 1.666667
a1 <- 0
a2 <- -0.3333333
f_x <- a0+a1*x+a2*x^2
```

```{r}
plot(x,f_x,col= "purple",
     type = "l",
     main =  "Grafica de una funcion ",
     xlab = "x",
     ylab = "f(x)")
abline(v = 0,type="-", col="black")
abline(h = 0,type="-", col="black")
```

```{r}
x<- seq(-5,5,0.1)
y1<- x+1;
y2<- (-1-5*x)/3
y3<- 2*x-1;

```

```{r}
par(new=t)
plot(x,y1,
     type="l",
     col="purple",
     xlab="",
     ylab="")
plot(x,y2,
     type="l",
     col="blue",
     xlab="",
     ylab="")
plot(x,y3,
     type="l",
     col="pink",
     xlab="",
     ylab="")

```