---
title: "Untitled"
output: html_document
date: "2025-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
A <- matrix (c(
  4,-1,0,0,0,
 -1,4,-1,0,0,
  0,-1,4,-1,0,
  0,0,-1,4,-1,
  0,0,0,-1,4
), nrow = 5, byrow = TRUE)
b <- c(1,2,3,4,5)
(A)
```


```{r}
x <- rep(0,5) #x^(0)=(0,0,0,0,0)
cat("x^(0) =", paste(sprintf("%.8f",x), collapse=","), "\n")

```

```{r}
x_old <- x
cat("\nIteración 1\n")
```

##
## ITERACIÓN 1

```{r}
x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(1) = (1+%g)/4= %.8f\n", x_old[2], x[1]))
```

```{r}
x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(1) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))
```

```{r}
x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(1) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

```
```{r}
x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(1) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

```

```{r}
x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(1) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

```
```{r}
r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(1) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))

```
## ITERACION 2


```{r}
x_old <- x
cat("\nIteración 2\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(2) = (1+%g)/4= %.8f\n", x_old[2], x[1]))



x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(2) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))



x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(2) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))


x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(2) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(2) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(1) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))

```

## ITERACIÓN 3


```{r}
x_old <- x
cat("\nIteración 3\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(3) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(3) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(3) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(3) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(3) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(1) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

## ITERACIÓN 4


```{r}
x_old <- x
cat("\nIteración 4\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(4) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(4) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(4) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(4) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(4) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(1) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

## ITERACIÓN 5


```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(5) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(5) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(5) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(5) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(5) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(5) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

## ITERACIÓN 6


```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(6) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(6) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(6) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(6) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(6) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(6) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

## ITERACIÓN 7


```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(7) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(7) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(7) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(7) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(7) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(7) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


## ITERACIÓN 8

```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(8) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(8) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(8) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(8) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(8) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(8) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```


## ITERACIÓN 9

```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(9) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(9) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(9) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(9) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(9) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(9) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```

## ITERACIÓN 10


```{r}
x_old <- x
cat("\nIteración 5\n")

x[1] <- (b[1]+ x_old[2]) / A[1,1]
cat(sprintf("x1^(10) = (1+%g)/4= %.8f\n", x_old[2], x[1]))

x[2] <- (b[2]+ x[1]+ x_old[2]) / A[2,2]
cat(sprintf("x2^(10) = (2+%.8f+%g)/4 = %.8f\n", x[1],x_old[3], x[2]))

x[3] <- (b[3]+ x[2]+ x_old[4]) / A[3,3]
cat(sprintf("x3^(10) = (3+%.8f+ %g)/4 = %.8f\n", x[2],x_old[4], x[3]))

x[4] <- (b[4]+ x[3]+ x_old[5]) / A[4,4]
cat(sprintf("x4^(10) = (4 + %.8f + %g)/4 = %.8f\n", x[3],x_old[5], x[4]))

x[5] <- (b[5]+ x[4]) / A[5,5]
cat(sprintf("x5^(10) = (5 + %.8f)/4 = %.8f\n", x[4],x[5]))

r <- b - A %*% x
dx_inf <- max(abs(x - x_old))
cat(sprintf("x^(10) = %s\n", paste(sprintf("%.8f",x), collapse = ", ")))
cat(sprintf("||dx||_inf = %.8e| ||r||_inf = %.8e\n", dx_inf, max(abs(r))))
```