---
title: "interpolacion ejercicio 13"
author: "Monserrath Antonio Cordero"
date: "2025-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 13

# Datos experimentales h = 10:
```{r}
x13 <- c(10,20,30,40,50)
y13 <- c(20.5,24.0,32.0,42.5,51.0)
print(data.frame(x = x13, y = y13))

# Verificar equiespaciados

print(paste("Diferencias entre x:", paste(diff(x13), collapse = ", ")))
```
# Diferencias progresivas hasta tercer orden
```{r}
dy13_1 <- diff(y13)
dy13_2 <- diff(dy13_1)
dy13_3 <- diff(dy13_2)
print("Δy:")
print(dy13_1)
print("Δ²y:")
print(dy13_2)
print("Δ³y:")
print(dy13_3)
```
# Estimar y(25) usando Newton hacia adelante
```{r}
h13 <- 10
p13 <- (25 - x13[1]) / h13
y0_13 <- y13[1]
term1_13 <- p13 * dy13_1[1]
term2_13 <- p13 * (p13 - 1) / 2 * dy13_2[1]
term3_13 <- p13 * (p13 - 1) * (p13 - 2) / 6 * dy13_3[1]
P13 <- y0_13 + term1_13 + term2_13 + term3_13
print(paste("P(25) =", P13))
```

```{r}
dy13_4 <- diff(dy13_3)
term4_13 <- p13 * (p13 - 1) * (p13 - 2) * (p13 - 3) / 24 * dy13_4[1]
print(paste("Término siguiente estimado ≈", term4_13))
print(paste("Magnitud ≈", abs(term4_13)))
```
